version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@x.y.z
jobs:
  delete:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - kubernetes/install-kubectl
      - kubernetes/delete-resource:
          now: true
          resource-names: nginx-deployment
          resource-types: deployments
          wait: true
