# Vagrant box for testing kind with cgroup v2
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://iad.mirror.rackspace.com/fedora/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-35-1.2.x86_64.vagrant-virtualbox.box"
  memory = 2048
  cpus = 2
  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    # Ensure network-related modules to be loaded
    modprobe tap ip_tables iptable_nat ip6_tables ip6table_nat

    dnf install -y make kubernetes-client moby-engine jq wget gcc
    # Setup custom golang as we need 1.17+
    wget https://go.dev/dl/go1.17.9.linux-amd64.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.9.linux-amd64.tar.gz
    echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile

    systemctl enable --now docker
    loginctl enable-linger vagrant
    SHELL
  end
  config.vm.provision "install-kind", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64
    chmod +x ./kind
    mv ./kind /usr/local/bin/
    SHELL
  end
end

