name: "KinD"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Testing on KinD
        run: |
          export GO111MODULE=on
          export PATH=$PATH:$(go env GOPATH)/bin
          # Print cluster info
          kubectl cluster-info
          kubectl get pods -n kube-system
          kubectl wait --for=condition=Ready pods --all -n kube-system
          kubectl get pods -n kube-system
          # Cert manager
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.0/cert-manager.yaml
          kubectl wait --for=condition=Ready pods --all -n cert-manager
          # flotta operator
          make build
          IMG=flotta-operator:latest make docker-build
          kind load docker-image flotta-operator:latest
          timeout 1m make deploy IMG=flotta-operator || retVal=$?
          if [ $retVal -ne 124 ]; then
            echo "Make run failed"; exit 1
          fi
          kubectl wait --timeout=120s --for=condition=Ready pods --all -n flotta
          kubectl port-forward deploy/flotta-operator-controller-manager -n flotta --address 0.0.0.0 8888:8888 &
          ## Setup edgedevice

          docker run --name device1 --privileged -d quay.io/machacekondra/flotta-worker
          for i in `seq 10`; do kubectl get edgedevices -A; sleep 5; done
          docker exec device1 journalctl -u yggdrasild
          kubectl logs deploy/flotta-operator-controller-manager -n flotta -c manager
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            mkdir dist
            kind export logs dist
